# -*- coding: utf-8 -*-
"""MA50-200.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KykzLzeszvGFbzsf2EJeiMmVYLydo_T

**Backtesting**

50-day MA aur 200-day MA calculate karna hai

Jab 50MA upar jaaye 200MA se → BUY (Golden Cross)

Jab 50MA neeche jaaye 200MA se → SELL
"""

import yfinance as yf
import pandas as pd
import pandas_ta as ta

!pip install yfinance pandas-ta

import matplotlib.pyplot as plt

!pip install matplotlib

df = yf.download("EURUSD=X", start = "2022-01-01" , end = "2025-01-01" , interval ="1d")
df.columns = df.columns.get_level_values(0)
df.dropna(inplace=True)
print(df.shape)

"""Calculating moving averages"""

df["MA50"] = df["Close"].rolling(window= 50).mean()
df["MA200"] = df["Close"].rolling(window = 200).mean()
print(df[["Close", "MA50", "MA200"]].tail(10))

"""Creating Signals"""

df["Signal"] = 0
df.loc[df["MA50"] > df["MA200"] ,"Signal"] = 1
df.loc[df["MA50"] < df["MA200"],"Signal"]= -1

print("Buy signals:", (df["Signal"] == 1).sum())
print("Sell signals:", (df["Signal"]== -1).sum())

"""Calculating returns"""

df["Return"] = df["Close"].pct_change()
df["Strategy_Return"] = df["Signal"].shift(1) * df["Return"]

cumulative = (1 + df["Strategy_Return"]).cumprod()
print("Final Portfolio Value:", cumulative.iloc[-1])

cumulative.plot(title="MA Crossover Strategy - Cumulative Returns")
plt.xlabel("Date")
plt.ylabel("Portfolio Value")
plt.grid(True)
plt.show()

total_return = cumulative.iloc[-1] - 1
sharpe = df["Strategy_Return"].mean() / df["Strategy_Return"].std() * (252**0.5)
max_dd = (cumulative / cumulative.cummax() - 1).min()

print(f"Total Return: {total_return*100:.2f}%")
print(f"Sharpe Ratio: {sharpe:.2f}")
print(f"Max Drawdown: {max_dd*100:.2f}%")